DROP DATABASE IF EXISTS zoo;
DROP DATABASE IF EXISTS library;
DROP DATABASE IF EXISTS school;
DROP DATABASE IF EXISTS transportation;
DROP DATABASE IF EXISTS gym;
DROP DATABASE IF EXISTS bank;

DROP ROLE IF EXISTS zookeeper;
DROP ROLE IF EXISTS librarian;
DROP ROLE IF EXISTS teacher;
DROP ROLE IF EXISTS conductor;
DROP ROLE IF EXISTS trainer;
DROP ROLE IF EXISTS teller;